#!/bin/sh

DIR=../test
cd ../examples && maude < replay.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/replay.out
diff $DIR/replay.expected $DIR/replay.out
rm $DIR/replay.out