#!/bin/sh

DIR=../test
cd ../examples && maude < twoteleport.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/twoteleport.out
diff $DIR/twoteleport.expected $DIR/twoteleport.out
rm $DIR/twoteleport.out