#!/bin/sh

DIR=../test
cd ../examples && maude < relay.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/relay.out
diff $DIR/relay.expected $DIR/relay.out
rm $DIR/relay.out