#!/bin/sh

DIR=../test
cd ../examples && maude < twoQteleport.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/twoQteleport.out
diff $DIR/twoQteleport.expected $DIR/twoQteleport.out
rm $DIR/twoQteleport.out