#!/bin/sh

DIR=../../test/prob
cd ../../examples/prob && maude < networkcoding.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/networkcoding.out
diff $DIR/networkcoding.expected $DIR/networkcoding.out
rm $DIR/networkcoding.out