#!/bin/sh

DIR=../../test/prob
cd ../../examples/prob && maude < secretsharing.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/secretsharing.out
diff $DIR/secretsharing.expected $DIR/secretsharing.out
rm $DIR/secretsharing.out