#!/bin/sh

DIR=../../test/prob
cd ../../examples/prob && maude < teleport.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/teleport.out
diff $DIR/teleport.expected $DIR/teleport.out
rm $DIR/teleport.out