#!/bin/sh

DIR=../../test/prob
cd ../../examples/prob && maude < twoteleport.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/twoteleport.out
diff $DIR/twoteleport.expected $DIR/twoteleport.out
rm $DIR/twoteleport.out